defaults:
  - data: ???
  - model: ???
  - output: default
  - train: default
  - mask: default
  - features: default
  - logging: default
  - _self_


seed: 42
runs_root: ${hydra:runtime.cwd}/outputs/${model.model_type}/${model.size}/${experiment}/runs
out_root: outputs/${model.model_type}/${model.size}/${experiment}

experiment: ???

train:
  run_id: null

# Make Hydra put the working dir for this run *inside* that structure
hydra:
  run:
    dir: ${out_root}
  job:
    chdir: true